server:
  port: 8888
spring:
  application:
    name: mszlu_blog
#数据库的配置
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/mszlu_blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 122112
    driver-class-name: com.mysql.cj.jdbc.Driver
#MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #可以打印日志
  global-config: #定义表名前缀
    db-config:
      table-prefix: ms_
